version: "3"

services:
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - my_network
    env_file:
      - ./.env


  suck_web:
    container_name: suck_pdf
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    entrypoint: ./wsgi-entrypoint.sh
    depends_on:
      - db
    networks:
      - my_network
    env_file:
      - ./.env

volumes:
  media:
  static:
  postgres_data:

networks:
  my_network:
